In [1]:
#!pip install qiskit
#!pip install qiskit_machine_learning
#!pip install pylatexenc

In [2]:
#Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from qiskit import Aer, QuantumCircuit
from qiskit.opflow import Z, I, StateFn
from qiskit.utils import QuantumInstance
from qiskit.circuit import Parameter
from qiskit.circuit.library import RealAmplitudes, ZZFeatureMap, ZFeatureMap
from qiskit.algorithms.optimizers import COBYLA, L_BFGS_B

from qiskit_machine_learning.neural_networks import TwoLayerQNN, CircuitQNN
from qiskit_machine_learning.algorithms.classifiers import NeuralNetworkClassifier, VQC
from qiskit_machine_learning.algorithms.regressors import NeuralNetworkRegressor, VQR

from typing import Union

from qiskit_machine_learning.exceptions import QiskitMachineLearningError
import pylatexenc

from sklearn.metrics import confusion_matrix

In [3]:
#Initiating the instance
quantum_instance = QuantumInstance(Aer.get_backend('qasm_simulator'), shots=1024)

In [4]:
#Reading the data and removing extra column unnamed
data = pd.read_csv("outputNH3.csv")
data.head()
data = data.drop("Unnamed: 0", axis = 1)
data.head()

BOD  NH3-N  TN  MLSS   PH  AT_Temp  NH3_Y                 Date
0   38     25  48  2250  8.3   22.150   0.98  2013-01-10 00:00:00
1  150     28  41  2190  7.4   22.975   0.59  2013-01-24 00:00:00
2  130     26  41  2090  7.2   22.750   0.57  2013-01-31 00:00:00
3  180     29  48  2500  7.6   25.200   0.78  2013-02-07 00:00:00
4  170     28  44  2040  7.3   24.175   0.72  2013-03-07 00:00:00

In [5]:
#Filtering data so it runs faster
#data = data.iloc[0:20,]

In [6]:
# Creating a binary variable based on median value
data['NH3_Y_binary'] = np.where(data['NH3_Y'] >= data['NH3_Y'].median(), 1, 0)
data.head()

BOD  NH3-N  TN  MLSS   PH  AT_Temp  NH3_Y                 Date  \
0   38     25  48  2250  8.3   22.150   0.98  2013-01-10 00:00:00   
1  150     28  41  2190  7.4   22.975   0.59  2013-01-24 00:00:00   
2  130     26  41  2090  7.2   22.750   0.57  2013-01-31 00:00:00   
3  180     29  48  2500  7.6   25.200   0.78  2013-02-07 00:00:00   
4  170     28  44  2040  7.3   24.175   0.72  2013-03-07 00:00:00   

   NH3_Y_binary  
0             1  
1             0  
2             0  
3             1  
4             1

In [7]:
#doing pandas profiling
from pandas_profiling import ProfileReport
profile = ProfileReport(data, title="Pandas Profiling Report")
profile.to_widgets()

Summarize dataset:   0%|          | 0/22 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
#Filtering relevant independent variables
X = data[['BOD','NH3-N','TN','MLSS','PH','AT_Temp']]
X.head()

BOD  NH3-N  TN  MLSS   PH  AT_Temp
0   38     25  48  2250  8.3   22.150
1  150     28  41  2190  7.4   22.975
2  130     26  41  2090  7.2   22.750
3  180     29  48  2500  7.6   25.200
4  170     28  44  2040  7.3   24.175

In [9]:
# Creating binary variable
y = data['NH3_Y_binary']

In [10]:
# Creating a dummy varible for VQC
y_new = np.ones((len(data),2))
print(y_new)

y_new[:,1] = np.where(y == 1, 1, 0)
y_new[:,0] = np.where(y == 0, 1, 0)
y_new

[[1. 1.]
 [1. 1.]
 [1. 1.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [11]:
# Y variable for regression and scaling it from -1 to +1
y_linear = data['NH3_Y']
y_linear_scaled = np.interp(y_linear, (y_linear.min(), y_linear.max()), (-1, +1))
y_linear_scaled

array([-0.31428571, -0.87142857, -0.9       , -0.6       , -0.68571429,
        0.14285714, -0.78571429, -0.92857143, -0.54285714, -0.71428571,
       -0.35714286,  1.        , -0.42857143, -0.9       , -0.61428571,
       -0.72857143, -0.84285714, -0.95714286, -0.82857143, -0.4       ,
       -0.91428571, -0.88571429, -0.81428571, -0.38571429, -0.65714286,
       -0.57142857, -0.88571429, -0.38571429, -0.61428571, -0.58571429,
       -0.98571429, -0.61428571, -0.94285714, -0.7       , -0.14285714,
       -0.28571429, -0.32857143, -0.85714286, -0.7       , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -1.        ,
       -1.        , -1.        , -1.        , -1.        , -0.61

In [12]:
# construct QNN
num_inputs = 6
opflow_qnn = TwoLayerQNN(num_inputs, quantum_instance=quantum_instance)

In [13]:
# QNN maps inputs to [-1, +1]
opflow_qnn.forward(X.iloc[0,:], np.random.rand(opflow_qnn.num_weights))

array([[0.140625]])

In [14]:
# construct neural network classifier
opflow_classifier = NeuralNetworkClassifier(opflow_qnn, optimizer=COBYLA())

In [ ]:
# fit classifier to data
opflow_classifier.fit(X, y)

In [ ]:
# evaluate data points
y_predict_opflow_classifier = opflow_classifier.predict(X)

# plot results
# red == wrongly classified
for x, y_target, y_p in zip(X, y, y_predict_opflow_classifier):
    if y_target == 1:
        plt.plot(x[0], x[1], 'bo')
    else:
        plt.plot(x[0], x[1], 'go')
    if y_target != y_p:
        plt.scatter(x[0], x[1], s=200, facecolors='none', edgecolors='r', linewidths=2)
plt.plot([-1, 1], [1, -1], '--', color='black')
plt.show()

In [ ]:
confusion_matrix(y,y_predict_opflow_classifier)

In [ ]:
# construct feature map
feature_map = ZFeatureMap(num_inputs)

# construct ansatz
ansatz = RealAmplitudes(num_inputs, reps=1)

# construct quantum circuit
qc = QuantumCircuit(num_inputs)
qc.append(feature_map, range(num_inputs))
qc.append(ansatz, range(num_inputs))
qc.decompose().draw(output='mpl')

In [ ]:
# parity maps bitstrings to 0 or 1
def parity(x):
    return '{:b}'.format(x).count('1') % 2
output_shape = 2  # corresponds to the number of classes, possible outcomes of the (parity) mapping.

In [ ]:
# construct QNN
circuit_qnn = CircuitQNN(circuit=qc,
                         input_params=feature_map.parameters,
                         weight_params=ansatz.parameters,
                         interpret=parity,
                         output_shape=output_shape,
                         quantum_instance=quantum_instance)

In [ ]:
# construct classifier
circuit_classifier = NeuralNetworkClassifier(neural_network=circuit_qnn,
                                             optimizer=COBYLA())

In [ ]:
# fit classifier to data
circuit_classifier.fit(X, y)

In [ ]:
# evaluate data points
y_predict_circuit_classifier = circuit_classifier.predict(X)

# plot results
# red == wrongly classified
for x, y_target, y_p in zip(X, y, y_predict_circuit_classifier):
    if y_target == 1:
        plt.plot(x[0], x[1], 'bo')
    else:
        plt.plot(x[0], x[1], 'go')
    if y_target != y_p:
        plt.scatter(x[0], x[1], s=200, facecolors='none', edgecolors='r', linewidths=2)
plt.plot([-1, 1], [1, -1], '--', color='black')
plt.show()

In [ ]:
confusion_matrix(y,y_predict_circuit_classifier)

VQC Classifier

In [ ]:
# construct feature map, ansatz, and optimizer
feature_map = ZZFeatureMap(num_inputs)
ansatz = RealAmplitudes(num_inputs, reps=1)

# construct variational quantum classifier
vqc = VQC(feature_map=feature_map,
          ansatz=ansatz,
          loss='cross_entropy',
          optimizer=COBYLA(),
          quantum_instance=quantum_instance)

In [ ]:
vqc.fit(X, y_new)

In [ ]:
# evaluate data points
y_predict = vqc.predict(X)

# plot results
# red == wrongly classified
for x, y_target, y_p in zip(X, y_new, y_predict):
    if y_target[0] == 1:
        plt.plot(x[0], x[1], 'bo')
    else:
        plt.plot(x[0], x[1], 'go')
    if not np.all(y_target == y_p):
        plt.scatter(x[0], x[1], s=200, facecolors='none', edgecolors='r', linewidths=2)
plt.plot([-1, 1], [1, -1], '--', color='black')
plt.show()

VQC Regression

In [ ]:
#Initiating regressor
vqr = VQR(feature_map=feature_map,
          ansatz=ansatz,
          optimizer=L_BFGS_B(),
          quantum_instance=quantum_instance)

In [ ]:
#fitting regressor
vqr.fit(X, y_linear_scaled)

In [ ]:
#Predicting the value
y_VQR = vqr.predict(X)
y_VQR

In [ ]:
# plot data
plt.plot(X.iloc[:,0], y_linear_scaled, 'bo')
# plot fitted line
plt.plot(X.iloc[:,0], y_VQR, 'go')
plt.show()

In [ ]:
plt.plot(y_linear_scaled,y_VQR, 'bo')
x = np.linspace(-1, 1,100)
plt.xlim([-1, 1])
plt.ylim([-1, 1])
plt.plot(x,x,color="black")

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
#MSE
mse = mean_squared_error(y_linear_scaled,y_VQR)
print(mse)
# R squared error
r2s = r2_score(y_linear_scaled,y_VQR)
print(r2s)